# .sops.yaml

keys:
  - &primary age12awywjkq4vz7vvl09drrz63y3knj48fpgehgz02y6ct079ckdcps7p9ezj
  - &yubikeys:
    - &MAIN age1yubikey1qwmsh9cyleu9awj7myytzp6tnz749s453alnpdlwp6ufcye5m8susp8g3l3
    - &BACK age1yubikey1q0tweg7yddprt8zjgc2cwpgps286zqg964kzg2a4vju9xwd7smpfg95p9md
  - &hosts:
    - &wsl age1j9266vjsp6r7vukc2ee3dtadk4kqwgc736j786vvmqttktnztvdqnnx83v
    - &box age1kxsfwgpu2wkaunpmq7gdhyya2zcfpg097w7dequjjkymqn65yuuqatsl3w
    - &thinkbook age1ac5yteuu76m0ur28r80qntr0njmnua2x7adrf39czjcfpu4auves0jwh2t
    - &ideapad age1zx4mqel8jwwzn4vzmr85aqqevea06kd9cl7q4n64wk8fslrpw59sgazk2g
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *primary
          - *wsl
          - *box
          - *thinkbook
          - *ideapad
          - *MAIN
          - *BACK
