# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "uas"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [
    "nvme"
    "vfat"
    "nls_cp437"
    "usbhid"
    "nls_iso8859-1"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [ "amd_pstate=active" ]; # AMD CPU power management

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false; # External drive
  boot.loader.efi.efiSysMountPoint = "/boot";

  # fileSystems."/" =
  #   { device = "/dev/mapper/cryptroot";
  #     fsType = "ext4";
  #   };
  #
  # boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/3e561523-14cd-4af6-b0f3-03f311f52952";
  # boot.initrd.luks.devices."cryptroot".allowDiscards = true; # SSD TRIM support
  #
  # fileSystems."/boot" =
  #   { device = "/dev/disk/by-uuid/05FC-B3C7";
  #     fsType = "vfat";
  #     options = [ "fmask=0022" "dmask=0022" ];
  #   };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  # AMD CPU optimizations
  hardware.cpu.amd.updateMicrocode = lib.mkForce true;
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # NVIDIA drivers
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    open = false; # Proprietary driver for gaming
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Graphics (OpenGL/Vulkan)
  hardware.graphics = {
    enable = true;
    enable32Bit = true; # For gaming
  };

}
